# Generated by Django 4.0.5 on 2022-07-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbolistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
