# Generated by Django 4.0.4 on 2022-06-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeSocio', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeIngreso', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
